#!/usr/bin/env python3
# encoding: utf-8
"""
base64

Created by Nicolas Strina on 2015-01-05.
Copyright (c) 2000-2015. All rights reserved.
"""

import sys
import base64

def Encrypt(arg):
	data = Query('Password: ')
	encoded = base64.b64encode(data.encode('ascii'))
	WriteFile(encoded)

def Decrypt(arg):
	print ('')
	print ('Decrypted password:')
	decoded = base64.b64decode(arg)
	print (decoded)

def ReadFile():
	with open('base64.pwd','r') as read_password:
		print ('')
		print ('Reading password ..')

		read = read_password.read()
		read_password.close()
		print (read)
		Decrypt(read)

def WriteFile(arg):
	with open('base64.pwd','w') as write_password:
		write = write_password.write(arg)
		write = write_password.close()
		print ('')
		print ('The password has been stored')

def Query(arg):
	sys.stdout.write(arg)
	sys.stdout.flush()
	return sys.stdin.readline().strip()

def MenuValidation(arg):
	if arg == '1':
		Encrypt(arg)
	elif arg == '2':
		ReadFile()

print ('##########################')
print ('# Welcome to base64.py ! #')
print ('##########################')
print ('')
print ('Please choose an option in the menu:')
print ('')
print ('1. Encrypt a password')
print ('2. Decrypt a password')
print ('')

menu = Query('What is your choice ? ')

MenuValidation(menu)
